### PR TITLE
Use Double Quotes

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
I know it's ugly to use double quotes because they need to be escaped but single quotes fail on Winblows.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
Thanks. I guess npm won't pull this without a version bump.

**Comment by dtjm** [comment]
I just bumped to v0.0.16 and published it so you should be able to pull that down @okonomiyaki3000

**Comment by dtjm** [comment]
It doesn't seem to work with current versions of Node though, due to changes in the Native v8 APIs.

**Comment by okonomiyaki3000** [comment]
Yeah, it got a little further but still didn't finish. Any plan to update for the new version?

**Comment by dtjm** [comment]
I looked at the https://github.com/nodejs/nan to make it work but it's over my head right now. No immediate plans to work on it but if you're so inclined I'd be happy to merge.

**Pull request merged**
